### ISSUE TITLE
use versioned deps in generated packages

### ISSUE THREAD

**Issue by devoncarew** [googleapis/google-cloud-dart#27]
We should use versioned deps in generated packages (we're currently using `any` for the version constraint).

That would convert something like:

```yaml
dependencies:
  google_cloud_gax: any
  google_cloud_protobuf: any

dev_dependencies:
  test: any
```

to:

```yaml
dependencies:
  google_cloud_gax: ^0.1.0
  google_cloud_protobuf: ^0.1.0

dev_dependencies:
  test: ^1.25.0
```
